---
- name: Deploy Tasks
  hosts: localhost
  tags:
    - deploy
  tasks:
    - name: Install web server
      package:
        name: apache2
        state: present


- name: Configure Tasks
  hosts: localhost
  tags: 
    - configure
  tasks:
    - name: Setup web page
      template:
        src: index.html.j2
        dest: /var/www/index.html
